#!/bin/zsh

command -v acpi >/dev/null 2>&1 || { echo >&2 "I require acpi but it's not installed.  Aborting."; exit 1; }

Battery=$(acpi -b | grep "Battery" | sed -nr '/Battery/s/.*(\<[[:digit:]]+%).*/\1/p')
Thermal=$(acpi -t | grep "Thermal" | sed -nr "s/.*(\<[[:digit:]]+\.[[:digit:]]) degrees.*/\1°C/p" )

echo "$Battery"
echo "$Thermal"
